#!/bin/sh
#SBATCH -A p31378
#SBATCH -p normal
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -t 18:00:00
#SBATCH --mem=0
#SBATCH --job-name="run_metaspades_B1"
#SBATCH --mail-user=stefaniehuttelmaier2024@u.northwestern.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/projects/b1052/Wells_b1042/Stefanie/NOB/BNRmeta/metaspades/metaspades_01.out
#SBATCH --error=/projects/b1052/Wells_b1042/Stefanie/NOB/BNRmeta/metaspades/metaspades_01.err


##note: I loaded a newer version of spades into my local directory to use the metaviral program. If you do not need
##something in spades that isn't available in the version on quest (3.14.1 at the time of this publication) replace
## lines 20-22 with: module load spades/3.14.1

module purge all
module load python/anaconda

cd /projects/p31378/SPAdes-3.15.2-Linux/bin

##note: if using quests version of spades remove 'python metaspades.py' and replace with 'spades --meta'
## other flags are for each paired end and the output directory, for more flags visit the spades github linked in the readme

python metaspades.py --pe1-1 /projects/p31378/BNRmeta/results/fastp/SRR6800319_1_trimmed.fastq.gz /
--pe1-2 /projects/p31378/BNRmeta/results/fastp/SRR6800319_2_trimmed.fastq.gz /
-o /projects/b1052/Wells_b1042/Stefanie/NOB/BNRmeta/metaspades/SRR6800324
